server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/y_lab
    password: 123123
    driver-class-name: org.postgresql.Driver
    username: testMan
  liquibase:
    liquibase-schema: public
    change-log: db.changelog/change-logs.xml
    default-schema: service_liquibase
